#!/usr/bin/env bash
# Build the wifi-eth-bridge image with pi-gen (Docker flavour).
#
#   ./build.sh                 full build
#   CONTINUE=1 ./build.sh      resume a previous (failed) build container
#   CLEAN=1 CONTINUE=1 ./build.sh   rebuild stage-bridge only (touch pi-gen/stage{0,1,2}/SKIP first)
#
# Pass-through env honoured by pi-gen's build-docker.sh: CONTINUE, PRESERVE_CONTAINER,
# CLEAN, PIGEN_DOCKER_OPTS, CONTAINER_NAME.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIGEN="${ROOT}/pi-gen"

if [ ! -f "${PIGEN}/build-docker.sh" ]; then
	echo ">> initialising pi-gen submodule"
	git -C "${ROOT}" submodule update --init
fi

if [ ! -f "${ROOT}/config.local" ]; then
	echo "!! ${ROOT}/config.local not found."
	echo "   cp config.local.example config.local   and fill in the secrets."
	exit 1
fi

# pi-gen only sees a single config file (mounted at /config in the container),
# so merge the committed config with the local secrets.
GEN="${ROOT}/.config.generated"
{
	echo "# GENERATED by build.sh from config + config.local -- do not edit"
	cat "${ROOT}/config"
	echo
	cat "${ROOT}/config.local"
} > "${GEN}"
chmod 600 "${GEN}"

# Sanity-check required values before spending an hour in Docker.
(
	set +u
	# shellcheck disable=SC1090
	source "${GEN}"
	: "${FIRST_USER_PASS:?FIRST_USER_PASS must be set in config.local}"
	: "${WPA_COUNTRY:?WPA_COUNTRY must be set in config.local (else WiFi stays disabled)}"
	if [ -n "${WIFI_SSID:-}" ] && { [ "${#WIFI_PSK}" -lt 8 ] || [ "${#WIFI_PSK}" -gt 63 ]; }; then
		echo "WIFI_PSK must be 8-63 characters"; exit 1
	fi
)

# Apply local patches to the pi-gen checkout (idempotent).
for p in "${ROOT}"/patches/*.patch; do
	[ -e "$p" ] || continue
	if git -C "${PIGEN}" apply --check "$p" 2>/dev/null; then
		echo ">> applying $(basename "$p")"
		git -C "${PIGEN}" apply "$p"
	elif git -C "${PIGEN}" apply --reverse --check "$p" 2>/dev/null; then
		echo ">> $(basename "$p") already applied"
	else
		echo "!! $(basename "$p") does not apply cleanly to pi-gen $(git -C "${PIGEN}" rev-parse --short HEAD)"
		exit 1
	fi
done

# Only export the image from stage-bridge, not the intermediate lite image.
touch "${PIGEN}/stage2/SKIP_IMAGES"
chmod +x "${ROOT}"/stage-bridge/prerun.sh "${ROOT}"/stage-bridge/*/*.sh

# The Dockerfile COPYs the pi-gen tree, so our stage (which lives outside the
# submodule) is bind-mounted into the container at the path STAGE_LIST expects.
export PIGEN_DOCKER_OPTS="${PIGEN_DOCKER_OPTS:-} --volume ${ROOT}/stage-bridge:/pi-gen/stage-bridge"

if [ "${DRY_RUN:-0}" = "1" ]; then echo ">> DRY_RUN: config OK, patches applied, would run build-docker.sh -c ${GEN}"; exit 0; fi
echo ">> building with pi-gen $(git -C "${PIGEN}" rev-parse --short HEAD)"
cd "${PIGEN}"
./build-docker.sh -c "${GEN}"

mkdir -p "${ROOT}/deploy"
cp -v "${PIGEN}"/deploy/*-bridge.img "${PIGEN}"/deploy/*-bridge.info "${ROOT}/deploy/" 2>/dev/null || true
echo ">> done. Images in ${ROOT}/deploy:"
ls -lh "${ROOT}/deploy"
