#!/bin/bash -e
# Turn the Pi into a WiFi -> Ethernet router (routed subnet, no NAT):
#   wlan0: DHCP client on the home LAN (NetworkManager, keyfile below)
#   eth0 : static BRIDGE_ETH_IP, dnsmasq serves DHCP/DNS to the device(s) behind it
#   IPv4 forwarding on. The home router needs a static route for the eth0
#   subnet pointing at this Pi's wlan0 address.
#   LAN <-> eth0 traffic is NOT NATed. Only internet-bound traffic from the
#   eth0 subnet is masqueraded (consumer routers won't NAT foreign subnets).

: "${BRIDGE_ETH_IF:=eth0}" "${BRIDGE_WLAN_IF:=wlan0}"
: "${BRIDGE_ETH_IP:=192.168.2.1}" "${BRIDGE_ETH_PREFIX:=24}"
: "${BRIDGE_DHCP_START:=192.168.2.10}" "${BRIDGE_DHCP_END:=192.168.2.100}" "${BRIDGE_DHCP_LEASE:=12h}"
: "${BRIDGE_ETH_NET:=192.168.2.0/24}" "${BRIDGE_HOME_LAN:=192.168.0.0/24}"

NM_DIR="${ROOTFS_DIR}/etc/NetworkManager/system-connections"
install -d -m 755 "${NM_DIR}"

# --- eth0: static, never a default route ------------------------------------
cat > "${NM_DIR}/eth0-lan.nmconnection" <<- NMEOF
	[connection]
	id=eth0-lan
	type=ethernet
	interface-name=${BRIDGE_ETH_IF}
	autoconnect=true
	autoconnect-priority=-999

	[ethernet]

	[ipv4]
	method=manual
	address1=${BRIDGE_ETH_IP}/${BRIDGE_ETH_PREFIX}
	never-default=true

	[ipv6]
	method=disabled
	addr-gen-mode=default

	[proxy]
NMEOF
chmod 600 "${NM_DIR}/eth0-lan.nmconnection"

# --- wlan0: join the home WiFi ----------------------------------------------
if [ -n "${WIFI_SSID:-}" ]; then
	cat > "${NM_DIR}/${WIFI_SSID}.nmconnection" <<- NMEOF
		[connection]
		id=${WIFI_SSID}
		type=wifi
		interface-name=${BRIDGE_WLAN_IF}
		autoconnect=true

		[wifi]
		mode=infrastructure
		ssid=${WIFI_SSID}

		[wifi-security]
		auth-alg=open
		key-mgmt=wpa-psk
		psk=${WIFI_PSK}

		[ipv4]
		method=auto

		[ipv6]
		method=auto
		addr-gen-mode=default

		[proxy]
	NMEOF
	chmod 600 "${NM_DIR}/${WIFI_SSID}.nmconnection"
	echo "wifi keyfile installed for SSID '${WIFI_SSID}'"
else
	echo "WIFI_SSID not set; no WiFi keyfile installed"
fi

# --- dnsmasq: DHCP + DNS on eth0 only ---------------------------------------
install -d -m 755 "${ROOTFS_DIR}/etc/dnsmasq.d"
{
	cat <<- DNSEOF
		# DHCP + DNS for the device(s) on ${BRIDGE_ETH_IF} only. Generated by pi-gen stage-bridge.
		interface=${BRIDGE_ETH_IF}
		bind-dynamic
		dhcp-range=${BRIDGE_DHCP_START},${BRIDGE_DHCP_END},${BRIDGE_DHCP_LEASE}
		dhcp-option=option:router,${BRIDGE_ETH_IP}
		dhcp-option=option:dns-server,${BRIDGE_ETH_IP}
		dhcp-authoritative
		log-dhcp
	DNSEOF
	if [ -n "${BRIDGE_DHCP_HOSTS:-}" ]; then
		echo "# Static reservations (mac,name,ip)"
		while IFS= read -r line; do
			line="${line// /}"
			[ -n "${line}" ] && echo "dhcp-host=${line}"
		done <<< "${BRIDGE_DHCP_HOSTS}"
	fi
} > "${ROOTFS_DIR}/etc/dnsmasq.d/eth0-lan.conf"
chmod 644 "${ROOTFS_DIR}/etc/dnsmasq.d/eth0-lan.conf"

# --- forwarding -------------------------------------------------------------
install -d -m 755 "${ROOTFS_DIR}/etc/sysctl.d"
echo 'net.ipv4.ip_forward=1' > "${ROOTFS_DIR}/etc/sysctl.d/99-ip-forward.conf"

# --- NAT for internet-bound traffic only ------------------------------------
cat > "${ROOTFS_DIR}/etc/nftables.conf" <<- NFTEOF
	#!/usr/sbin/nft -f
	# Generated by pi-gen stage-bridge.
	# Home LAN <-> ${BRIDGE_ETH_NET} is routed as-is (no NAT) so hosts behind the
	# Pi keep their real addresses. Only internet-bound traffic from
	# ${BRIDGE_ETH_NET} is masqueraded, because the home router will not NAT
	# sources outside its own LAN subnet.
	flush ruleset

	table ip nat {
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			oifname "${BRIDGE_WLAN_IF}" ip saddr ${BRIDGE_ETH_NET} ip daddr != { ${BRIDGE_HOME_LAN}, ${BRIDGE_ETH_NET} } masquerade
		}
	}
NFTEOF
chmod 755 "${ROOTFS_DIR}/etc/nftables.conf"

on_chroot <<- CHEOF
	systemctl enable dnsmasq
	systemctl enable nftables
	systemctl enable NetworkManager
CHEOF
